# Public ICS calendar for demonstration. This can be replaced with your own calendars
calendars:
  - url: "https://ics.calendarlabs.com/76/73350498/US_Holidays.ics"

timezone-format: "America/New_York"